<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>Gay.TCazier.Resume.$(MSBuildProjectName.Replace(" ", "_"))</RootNamespace>
    <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
    <VersionPrefix>1.0.0</VersionPrefix>
    <VersionSuffix>alpha-1.0.3</VersionSuffix>
    <PackageId>Gay.TCazier.pkg.Resume.$(AssemblyName)</PackageId>
    <Title>Resume API Buisness Logic Layer</Title>
    <PackageProjectUrl>tcazier.gay</PackageProjectUrl>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <AssemblyVersion>$(VersionPrefix).0</AssemblyVersion>
    <FileVersion>$(VersionPrefix).0</FileVersion>
    <PackageLicenseFile>LICENSE</PackageLicenseFile>
    <PackageRequireLicenseAcceptance>True</PackageRequireLicenseAcceptance>
    <PackageReleaseNotes>
      # VERSION 1.0.0-alpha-1.0.3
      - Update gitignore
      - Update dependencies
    </PackageReleaseNotes>
    <PackageIcon>icon.png</PackageIcon>
    <AssemblyName>Resume.$(MSBuildProjectName)</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="icon.png" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Gay.TCazier.pkg.Resume.Contracts" Version="1.0.0-alpha-1.2.2" />
    <PackageReference Include="Refit" Version="8.0.0" />
    <PackageReference Include="Refit.HttpClientFactory" Version="8.0.0" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\LICENSE">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
    <None Include="..\README.md">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
    <None Update="1738852015508output.png">
      <Pack>True</Pack>
      <PackagePath></PackagePath>
    </None>
    <None Update="icon.png">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>

</Project>
